### ISSUE TITLE
Add "omero" topic?

### ISSUE THREAD

**Issue by joshmoore** [MontpellierRessourcesImagerie/OMERO-metrics#3]
@juliomateoslangerak @Wapaa _et al._

A quick heads up that if you add a topic starting with `omero-` that the community will be able to find your plugin more easily.

The current [list](https://github.com/search?q=omero&type=topics&p=2) includes:

* [omero](https://github.com/topics/omero)
* [omero-api](https://github.com/topics/omero-api)
* [omero-archive](https://github.com/topics/omero-archive)
* [omero-asyncio](https://github.com/topics/omero-asyncio)
* [omero-cli](https://github.com/topics/omero-cli)
* [omero-cli-plugin](https://github.com/topics/omero-cli-plugin)
* [omero-configuration](https://github.com/topics/omero-configuration)
* [omero-download](https://github.com/topics/omero-download)
* [omero-import](https://github.com/topics/omero-import)
* [omero-server](https://github.com/topics/omero-server)
* [omero-py](https://github.com/topics/omero-py)
* [omero-web](https://github.com/topics/omero-web)-app
* [omero-scripts](https://github.com/topics/omero-scripts)
* [omero-sharing](https://github.com/topics/omero-sharing)
* [omero-training](https://github.com/topics/omero-training)

but of course you can add your own. :smile: Thanks!

You can see https://github.com/Laura190/OMEROimport/issues/1 for more information.

**Comment by juliomateoslangerak** [comment]
Yep. omero-metrics is now a topic too.

Thanks!!
